require whole "grocer" gem
otherwise you won't load "lib/grocer.rb"
and you'll see "NoMethodError (undefined method `pusher' for Grocer:Module):" error.